### ISSUE TITLE
Investigate Login Spam [dev]

### ISSUE THREAD

**Issue by Lewdcario** [Progressive-Victory/crm-bot#112]
```
0|crm-bot  | Error: Not enough sessions remaining to spawn 1 shards; only 0 remaining; resets at 2024-02-01T04:41:23.989Z
0|crm-bot  |     at WebSocketManager.connect (/home/lewd/crm-bot/node_modules/@discordjs/ws/src/ws/WebSocketManager.ts:299:10)
0|crm-bot  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|crm-bot  |     at WebSocketManager.connect (/home/lewd/crm-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:207:5)
0|crm-bot  |     at ExtendedClient.login (/home/lewd/crm-bot/node_modules/discord.js/src/client/Client.js:226:7)
0|crm-bot  |     at start (/home/lewd/crm-bot/src/index.ts:69:2)
```

**Comment by Lewdcario** [comment]
Fixed with 8a15c743193661d8df2e8fb9b81e7cf78a3507ef
